window.portfolioData = {
  profile: {
    name: "Vishu Vishal Banotra",
    title: "Full-stack Developer",
    email: "banotravishu89@gmail.com",
    github: "https://github.com/vishubanotra98",
    linkedin: "https://linkedin.com/in/vishu-vishal-banotra-107828160",
  },
  skills: [
    {
      title: "Languages",
      icon: "code-2",
      items: ["JavaScript", "TypeScript", "SQL", "HTML5", "CSS3"],
    },
    {
      title: "Frontend",
      icon: "layout-dashboard",
      items: [
        "React",
        "Next.js",
        "Redux Toolkit",
        "React Router",
        "Tailwind CSS",
        "Material UI",
        "SASS",
      ],
    },
    {
      title: "Backend",
      icon: "server",
      items: ["Node.js", "Express.js", "JWT", "Google OAuth 2.0", "REST APIs"],
    },
    {
      title: "Database",
      icon: "database",
      items: [
        "PostgreSQL",
        "MongoDB",
        "Prisma ORM",
        "Mongoose",
        "Redis",
        "BullMQ",
      ],
    },
    {
      title: "Tools",
      icon: "terminal",
      items: ["Git", "GitHub", "Docker", "Postman"],
    },
  ],
  experience: [
    {
      period: "Jul 2024 – Nov 2025",
      role: "Software Developer",
      company: "Vodex.ai • Bangalore",
      bullets: [
        "Designed and developed the complete UI/UX flow for an AI agentic calling workflow builder from scratch, creating a data-dense visual interface for configuring workflow triggers, actions, conditions, delays, webhooks, and workflow transitions using ReactFlow v11.",
        "Engineered the dynamic workflow editor using ReactFlow v11 and Redux Toolkit, implementing configurable node creation, dynamic node insertion and reconnection, and synchronized node/edge state management.",
        "Implemented a hybrid RSA–AES encryption layer to secure API communication, combining asymmetric key exchange with symmetric encryption for efficient payload protection.",
        "Rebuilt the legacy application UI using React.js and Material UI (MUI), translating Figma designs into reusable, responsive components and establishing consistent UI patterns across the platform.",
        "Worked closely with backend engineers to coordinate API contracts and data flows, integrate frontend functionality with backend services, and troubleshoot cross-layer issues to deliver features reliably.",
      ],
      stack: [
        "React.Js",
        "Next.Js",
        "Node.Js",
        "TypeScript",
        "Redux Toolkit",
        "ReactFlow",
        "Material UI",
        "REST APIs",
      ],
    },
  ],
  projects: [
    {
      name: "Subtend",
      type: "Personal Project",
      year: "2026 - Ongoing",
      description:
        "A full-stack team collaboration platform built around workspaces, teams, projects and issues, designed to give teams a simple place to organize work and track everything happening around it.",
      highlights: [
        "Built a workspace, team, project, issue structure with role-based access control, custom status workflows.",
        "Built a complete authentication system with short lived JWT access tokens, rotating refresh tokens, HTTP-only cookies and custom Google OAuth 2.0.",
        "Implemented workspace invitations and OTP verification with Resend, Redis and BullMQ, moving email delivery into background workers.",
        "Built an issue attention system that identifies issues needing attention based on blockers, overdue dates, priority, staleness and assignment state.",
        "Built workspace activity tracking with before/after snapshots for issue changes, making it possible to see how an issue has changed over time.",
        "Implemented a complete deletion lifecycle for teams and projects with soft deletion, Trash based recovery, restoration and scheduled permanent deletion through background jobs.",
        "Integrated GitHub at the project level with repository connections and webhooks, tracking commits pushed to main and merged pull requests and linking them to issues through ticket numbers.",
        "Built the backend with PostgreSQL, Prisma and Express.js, with authorization enforced across workspace, team, project and issue boundaries.",
      ],
      stack: [
        "Next.js",
        "TypeScript",
        "Node.js",
        "Express.js",
        "PostgreSQL",
        "Prisma ORM",
        "Redis",
        "BullMQ",
        "Tailwind CSS",
      ],
      liveUrl: "https://subtend.vishubanotra.xyz/",
      repositories: {
        frontend: "https://github.com/vishubanotra98/subtend-web",
        backend: "https://github.com/vishubanotra98/subtend-api",
      },
    },
    {
      name: "The Cake Shop",
      type: "Personal Project",
      year: "2023",
      description:
        "A MERN-based e-commerce application with product management, secure authentication and online payment integration.",
      highlights: [
        "Integrated Razorpay to support secure online payments.",
        "Implemented JWT authentication and role-based access control for users and administrators.",
        "Built REST APIs using Express.js and MongoDB with a responsive React frontend powered by Redux.",
      ],
      stack: [
        "React",
        "Redux",
        "Node.js",
        "Express.js",
        "MongoDB",
        "JWT",
        "Razorpay API",
      ],
      liveUrl: "https://thecakeshopp.vercel.app/",
      repositories: {
        frontend: "https://github.com/vishubanotra98/TheCakeShop",
        backend: "https://github.com/vishubanotra98/cakeShop-restApi",
      },
    },
  ],
};
